# Generated by Django 3.2.6 on 2021-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_banner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='category')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='media'),
        ),
    ]
