# Generated by Django 3.2.6 on 2021-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_auto_20210823_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(max_length=10)),
                ('message', models.TextField()),
                ('created_date', models.PositiveIntegerField()),
            ],
        ),
    ]
